# -*- coding: utf-8 -*-
"""Copy of Untitled70.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m4wuesdfSzMsuswvm7S2OcV598eEyH_7
"""

f=open("test.txt", "w") 
s=f.write("good morning to all")
print(s)

def file_read(fname):
            from itertools import islice
            with open(fname,"w") as myfile:
                                             myfile.write("Colab website")
            txt=open(fname)
            print(txt.read())
file_read('test.txt')

def file_read(fname):
                      with open(fname,"r") as myfile:
                                                      data=myfile.readlines()
                                                      print(data)
file_read("test.txt")

f=open("test.txt","w")
def file(fname):
                  import os
                  statinfo=os.stat(fname)
                  return statinfo.st_size
print("file size is",file("test.txt"))

def file_read(fname):
       with open(fname) as f:
           content_list=f.readlines()
           print(content_list)
file_read('test.txt')

a_file=open("test.txt")
number_of_lines=3
for i in range(number_of_lines):
             line=a_file.readline()
             print(line)

with open("test.txt") as f:
  with open("out.txt","w") as f1:
    for line in f:
      f1.write(line)
print(line)